import uuid
import sys
import random
from fastapi.testclient import TestClient

from app.main import app
from app.db.session import SessionLocal
from app.models.user import User
from app.models.repository import Repository
from app.models.github_connection import GitHubConnection
from app.models.notification import Notification
from app.models.finding import Finding
from unittest.mock import patch, AsyncMock
from app.monitoring.analyzer_base import FindingDraft

def run_verification():
    print("Testing manual-trigger for finding dispatch")
    with TestClient(app) as client:
        db = SessionLocal()
        try:
            db.query(Notification).delete()
            db.query(Finding).delete()
            db.commit()

            user_id = uuid.uuid4()
            user = User(
                id=user_id,
                email=f"tester_{user_id.hex}@example.com",
                auth_provider="test",
                is_active=True
            )
            db.add(user)
            db.commit()

            installation = GitHubConnection(
                user_id=user.id,
                installation_id=random.randint(100000, 999999),
                account_login="tester",
                account_type="User"
            )
            db.add(installation)
            db.commit()

            repo_id = uuid.uuid4()
            repo = Repository(
                id=repo_id,
                connection_id=installation.id,
                github_repo_id=random.randint(100000, 999999),
                full_name="test/test-repo",
                monitoring_enabled=True,
                default_branch="main"
            )
            db.add(repo)
            db.commit()

            app.dependency_overrides.clear()
            from app.auth.dependencies import get_current_user
            def override_get_user():
                return user
            app.dependency_overrides[get_current_user] = override_get_user
            
            mock_finding = FindingDraft(
                category="security",
                type_="vulnerability",
                title="Critical Mock",
                description="Generated by mock.",
                severity="critical",
                evidence={},
                fingerprint="mock-critical-1"
            )
            
            with patch('app.monitoring.analyzers.security_analyzer.SecurityAnalyzer.analyze', new_callable=AsyncMock) as mock_analyze:
                mock_analyze.return_value = [mock_finding]
                
                print("\n--- FIRST RUN (New Findings) ---")
                resp = client.post(
                    f"/api/v1/repositories/{repo_id}/monitor-runs",
                    json={"analyzer_key": "security"}
                )
                if resp.status_code == 200:
                    print("Security Analyzer Triggered successfully.")
                else:
                    print(f"Error {resp.status_code}: {resp.text}")

                findings = db.query(Finding).filter(Finding.repository_id == repo_id).all()
                print(f"Findings created: {len(findings)}")
                notifications = db.query(Notification).filter(Notification.user_id == user_id).all()
                print(f"Notifications generated: {len(notifications)}")
                
                print("\n--- SECOND RUN (Re-detection) ---")
                resp2 = client.post(
                    f"/api/v1/repositories/{repo_id}/monitor-runs",
                    json={"analyzer_key": "security"}
                )
                
                findings2 = db.query(Finding).filter(Finding.repository_id == repo_id).all()
                print(f"Findings in DB: {len(findings2)}")
                notifications2 = db.query(Notification).filter(Notification.user_id == user_id).all()
                print(f"Notifications generated after re-run: {len(notifications2)}")
                
                if len(notifications) > 0 and len(notifications) == len(notifications2):
                    print("\nSUCCESS! Notification was not duplicated on re-detection.")
                    return 0
                else:
                    print("\nFAILED! Duplicates found or no notifications generated.")
                    return 1

        finally:
            db.rollback()
            db.close()

if __name__ == "__main__":
    sys.exit(run_verification())
