"""Add notification preferences

Revision ID: 1de15b225693
Revises: c2f4a8d91e73
Create Date: 2026-09-21 21:15:08.008290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1de15b225693'
down_revision: Union[str, Sequence[str], None] = 'c2f4a8d91e73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_preferences',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('email_enabled', sa.BOOLEAN(), nullable=False),
    sa.Column('min_severity_email', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_preferences_user_id'), 'notification_preferences', ['user_id'], unique=True)
    op.drop_index(op.f('ix_ai_analyses_finding_requested_at'), table_name='ai_analyses')
    op.create_index('ix_ai_analyses_finding_requested_at', 'ai_analyses', ['finding_id', sa.literal_column('requested_at DESC')], unique=False)
    op.drop_index(op.f('ix_bot_interactions_repo_created_desc'), table_name='bot_interactions')
    op.create_index('ix_bot_interactions_repo_created_desc', 'bot_interactions', ['repository_id', sa.literal_column('created_at DESC')], unique=False)
    # op.create_index(op.f('ix_bot_interactions_repository_id'), 'bot_interactions', ['repository_id'], unique=False)
    op.drop_index(op.f('ix_repository_health_snapshots_repo_computed_at'), table_name='repository_health_snapshots')
    op.create_index('ix_repository_health_snapshots_repo_computed_at', 'repository_health_snapshots', ['repository_id', sa.literal_column('computed_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_repository_health_snapshots_repo_computed_at', table_name='repository_health_snapshots')
    op.create_index(op.f('ix_repository_health_snapshots_repo_computed_at'), 'repository_health_snapshots', ['repository_id', 'computed_at'], unique=False)
    op.drop_index(op.f('ix_notification_preferences_user_id'), table_name='notification_preferences')
    op.drop_index(op.f('ix_bot_interactions_repository_id'), table_name='bot_interactions')
    op.drop_index('ix_bot_interactions_repo_created_desc', table_name='bot_interactions')
    op.create_index(op.f('ix_bot_interactions_repo_created_desc'), 'bot_interactions', ['repository_id', 'created_at'], unique=False)
    op.drop_index('ix_ai_analyses_finding_requested_at', table_name='ai_analyses')
    op.create_index(op.f('ix_ai_analyses_finding_requested_at'), 'ai_analyses', ['finding_id', 'requested_at'], unique=False)
    op.drop_table('notification_preferences')
    # ### end Alembic commands ###
