"""Add RepositoryHealthSnapshot

Revision ID: 269a9cafb147
Revises: 927cc85b5a67
Create Date: 2026-09-15 01:02:41.269277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '269a9cafb147'
down_revision: Union[str, Sequence[str], None] = '927cc85b5a67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repository_health_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('repository_id', sa.Uuid(), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=False),
    sa.Column('category_scores', sa.JSON(), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repository_health_snapshots_repository_id'), 'repository_health_snapshots', ['repository_id'], unique=False)
    op.create_index('ix_repository_health_snapshots_repo_computed_at', 'repository_health_snapshots', ['repository_id', sa.text('computed_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_repository_health_snapshots_repo_computed_at', table_name='repository_health_snapshots')
    op.drop_index(op.f('ix_repository_health_snapshots_repository_id'), table_name='repository_health_snapshots')
    op.drop_table('repository_health_snapshots')
    # ### end Alembic commands ###
