"""Add remediation fields phase 13

Revision ID: 6dbcd9a73647
Revises: d501d16fe567
Create Date: 2026-09-23 03:02:02.329937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dbcd9a73647'
down_revision: Union[str, Sequence[str], None] = 'd501d16fe567'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_analyses_finding_requested_at'), table_name='ai_analyses')
    op.create_index('ix_ai_analyses_finding_requested_at', 'ai_analyses', ['finding_id', sa.literal_column('requested_at DESC')], unique=False)
    op.drop_index(op.f('ix_bot_interactions_repo_created_desc'), table_name='bot_interactions')
    op.create_index('ix_bot_interactions_repo_created_desc', 'bot_interactions', ['repository_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_bot_interactions_repository_id'), 'bot_interactions', ['repository_id'], unique=False)
    op.add_column('findings', sa.Column('remediation_status', sa.String(), nullable=False, server_default='pending'))
    op.add_column('findings', sa.Column('github_pr_id', sa.String(), nullable=True))
    op.add_column('findings', sa.Column('pr_url', sa.String(), nullable=True))
    op.add_column('findings', sa.Column('pr_number', sa.Integer(), nullable=True))
    op.add_column('findings', sa.Column('branch_name', sa.String(), nullable=True))
    op.add_column('findings', sa.Column('patch_summary', sa.Text(), nullable=True))
    op.drop_index(op.f('ix_repository_health_snapshots_repo_computed_at'), table_name='repository_health_snapshots')
    op.create_index('ix_repository_health_snapshots_repo_computed_at', 'repository_health_snapshots', ['repository_id', sa.literal_column('computed_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_repository_health_snapshots_repo_computed_at', table_name='repository_health_snapshots')
    op.create_index(op.f('ix_repository_health_snapshots_repo_computed_at'), 'repository_health_snapshots', ['repository_id', 'computed_at'], unique=False)
    op.drop_column('findings', 'patch_summary')
    op.drop_column('findings', 'branch_name')
    op.drop_column('findings', 'pr_number')
    op.drop_column('findings', 'pr_url')
    op.drop_column('findings', 'github_pr_id')
    op.drop_column('findings', 'remediation_status')
    op.drop_index(op.f('ix_bot_interactions_repository_id'), table_name='bot_interactions')
    op.drop_index('ix_bot_interactions_repo_created_desc', table_name='bot_interactions')
    op.create_index(op.f('ix_bot_interactions_repo_created_desc'), 'bot_interactions', ['repository_id', 'created_at'], unique=False)
    op.drop_index('ix_ai_analyses_finding_requested_at', table_name='ai_analyses')
    op.create_index(op.f('ix_ai_analyses_finding_requested_at'), 'ai_analyses', ['finding_id', 'requested_at'], unique=False)
    # ### end Alembic commands ###
