"""Add Finding lifecycle fields

Revision ID: 927cc85b5a67
Revises: 7b374731863f
Create Date: 2026-09-14 01:36:23.345063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '927cc85b5a67'
down_revision: Union[str, Sequence[str], None] = '7b374731863f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('findings', sa.Column('priority', sa.String(), nullable=True))
    op.add_column('findings', sa.Column('fingerprint', sa.String(), nullable=True))
    op.add_column('findings', sa.Column('acknowledged_at', sa.DateTime(), nullable=True))
    op.add_column('findings', sa.Column('resolved_at', sa.DateTime(), nullable=True))
    op.add_column('findings', sa.Column('resolution_source', sa.String(), nullable=True))
    op.create_index('ix_finding_repository_id_fingerprint_open', 'findings', ['repository_id', 'fingerprint'], unique=True, postgresql_where=sa.text("status = 'open' AND fingerprint IS NOT NULL"), sqlite_where=sa.text("status = 'open' AND fingerprint IS NOT NULL"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_finding_repository_id_fingerprint_open', table_name='findings', postgresql_where=sa.text("status = 'open' AND fingerprint IS NOT NULL"), sqlite_where=sa.text("status = 'open' AND fingerprint IS NOT NULL"))
    op.drop_column('findings', 'resolution_source')
    op.drop_column('findings', 'resolved_at')
    op.drop_column('findings', 'acknowledged_at')
    op.drop_column('findings', 'fingerprint')
    op.drop_column('findings', 'priority')
    # ### end Alembic commands ###
