"""Add AIConnection model

Revision ID: a75c01a3b1c0
Revises: 269a9cafb147
Create Date: 2026-09-15 20:20:16.455106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a75c01a3b1c0'
down_revision: Union[str, Sequence[str], None] = '269a9cafb147'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_connections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('encrypted_api_key', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('last_validated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_connections_user_id'), 'ai_connections', ['user_id'], unique=True)
    op.drop_index(op.f('ix_repository_health_snapshots_repo_computed_at'), table_name='repository_health_snapshots')
    op.create_index('ix_repository_health_snapshots_repo_computed_at', 'repository_health_snapshots', ['repository_id', sa.literal_column('computed_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_repository_health_snapshots_repo_computed_at', table_name='repository_health_snapshots')
    op.create_index(op.f('ix_repository_health_snapshots_repo_computed_at'), 'repository_health_snapshots', ['repository_id', 'computed_at'], unique=False)
    op.drop_index(op.f('ix_ai_connections_user_id'), table_name='ai_connections')
    op.drop_table('ai_connections')
    # ### end Alembic commands ###
