"""Add notification model

Revision ID: d501d16fe567
Revises: 1de15b225693
Create Date: 2026-09-21 22:06:01.512552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd501d16fe567'
down_revision: Union[str, Sequence[str], None] = '1de15b225693'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('repository_id', sa.Uuid(), nullable=True),
    sa.Column('notification_type', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('reference_type', sa.String(), nullable=False),
    sa.Column('reference_id', sa.String(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('email_status', sa.String(), nullable=False),
    sa.Column('email_sent_at', sa.DateTime(), nullable=True),
    sa.Column('email_error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("email_status IN ('not_applicable', 'pending', 'sent', 'failed')", name='ck_notifications_email_status'),
    sa.CheckConstraint("notification_type IN ('finding_created', 'health_score_dropped')", name='ck_notifications_notification_type'),
    sa.CheckConstraint("reference_type IN ('finding', 'health_snapshot')", name='ck_notifications_reference_type'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_repository_id'), 'notifications', ['repository_id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index('ix_notifications_user_id_read_at', 'notifications', ['user_id', 'read_at'], unique=False)
    op.drop_index(op.f('ix_ai_analyses_finding_requested_at'), table_name='ai_analyses')
    op.create_index('ix_ai_analyses_finding_requested_at', 'ai_analyses', ['finding_id', sa.literal_column('requested_at DESC')], unique=False)
    op.drop_index(op.f('ix_bot_interactions_repo_created_desc'), table_name='bot_interactions')
    op.create_index('ix_bot_interactions_repo_created_desc', 'bot_interactions', ['repository_id', sa.literal_column('created_at DESC')], unique=False)
    op.drop_index(op.f('ix_repository_health_snapshots_repo_computed_at'), table_name='repository_health_snapshots')
    op.create_index('ix_repository_health_snapshots_repo_computed_at', 'repository_health_snapshots', ['repository_id', sa.literal_column('computed_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_repository_health_snapshots_repo_computed_at', table_name='repository_health_snapshots')
    op.create_index(op.f('ix_repository_health_snapshots_repo_computed_at'), 'repository_health_snapshots', ['repository_id', 'computed_at'], unique=False)
    op.drop_index('ix_bot_interactions_repo_created_desc', table_name='bot_interactions')
    op.create_index(op.f('ix_bot_interactions_repo_created_desc'), 'bot_interactions', ['repository_id', 'created_at'], unique=False)
    op.drop_index('ix_ai_analyses_finding_requested_at', table_name='ai_analyses')
    op.create_index(op.f('ix_ai_analyses_finding_requested_at'), 'ai_analyses', ['finding_id', 'requested_at'], unique=False)
    op.drop_index('ix_notifications_user_id_read_at', table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_repository_id'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
