"""Add BotInteraction model

Revision ID: f1d5bb3861c2
Revises: 5a70e50d3c97
Create Date: 2026-09-16 19:01:49.628406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1d5bb3861c2'
down_revision: Union[str, Sequence[str], None] = '5a70e50d3c97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_interactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('repository_id', sa.Uuid(), nullable=False),
    sa.Column('github_event_id', sa.Uuid(), nullable=False),
    sa.Column('requester_github_login', sa.String(), nullable=False),
    sa.Column('intent', sa.String(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('skip_reason', sa.String(), nullable=True),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('github_reply_comment_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['github_event_id'], ['github_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.CheckConstraint("intent IN ('ci_status', 'pr_summary', 'repo_attention', 'issue_explain', 'unknown')", name='ck_bot_interactions_intent'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bot_interactions_created_at'), 'bot_interactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_bot_interactions_github_event_id'), 'bot_interactions', ['github_event_id'], unique=True)
    op.create_index('ix_bot_interactions_repo_created_desc', 'bot_interactions', ['repository_id', sa.text('created_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_bot_interactions_repo_created_desc', table_name='bot_interactions')
    op.drop_index(op.f('ix_bot_interactions_github_event_id'), table_name='bot_interactions')
    op.drop_index(op.f('ix_bot_interactions_created_at'), table_name='bot_interactions')
    op.drop_table('bot_interactions')
    # ### end Alembic commands ###
